function feat_vec=features_toolbox_ACA(y,Fs)
addpath('C:\Users\Asus\Documents\UNIVERSIDADE\Tese\Matlab\Apps and packages (External)\ACA-Code-master\ACA-Code-master\')

[centroid,~] = ComputeFeature('SpectralCentroid',y, Fs);
[crestFactor,~] = ComputeFeature('SpectralCrestFactor',y, Fs);
[flatness,~] = ComputeFeature('SpectralFlatness',y, Fs);
[flux,~] = ComputeFeature('SpectralFlux',y, Fs);
[kurtos,~] = ComputeFeature('SpectralKurtosis',y, Fs);
%[mfccs,~] = ComputeFeature('SpectralMfccs',y, Fs);
[pitchChroma,~] = ComputeFeature('SpectralPitchChroma',y, Fs);
[rollOff,~] = ComputeFeature('SpectralRolloff',y, Fs);
[skew,~] = ComputeFeature('SpectralSkewness',y, Fs);
[slope,~] = ComputeFeature('SpectralSlope',y, Fs);
[spread,~] = ComputeFeature('SpectralSpread',y, Fs);
[decrease,~] = ComputeFeature('SpectralDecrease',y, Fs);
[TonalPR,~] = ComputeFeature('SpectralTonalPowerRatio',y, Fs);
%[acfCoeff,~] = ComputeFeature('TimeAcfCoeff',y, Fs);
%[maxAcf,t] = ComputeFeature('TimeMaxAcf',y, Fs);
%[envelope,t] = ComputeFeature('TimePeakEnvelope',y, Fs);
%[predictivity,~] = ComputeFeature('TimePredictivityRatio',y, Fs);
[RMS,~] = ComputeFeature('TimeRms',y, Fs);
[time_std,~] = ComputeFeature('TimeStd',y, Fs);
[zcr,~] = ComputeFeature('TimeZeroCrossingRate',y, Fs);

% feat_vec=[mean(centroid),mean(crestFactor),mean(flatness),mean(flux),mean(kurtos),mean(mfccs,2)',mean(pitchChroma,2)',mean(rollOff),...
%      mean(skew),mean(slope),mean(spread),mean(TonalPR),mean(RMS),mean(std),mean(zcr)];
  
%feat_vec=[median(centroid),median(crestFactor),median(flatness),median(flux),median(kurtos),median(pitchChroma,2)',median(rollOff),...
%      median(skew),median(slope),median(spread),median(TonalPR),median(RMS),median(std),median(zcr)];
  
 feat_vec=[mean(centroid),max(centroid),min(centroid),median(centroid),std(centroid),...
           mean(crestFactor),max(crestFactor),min(crestFactor),median(crestFactor),std(crestFactor),...
           mean(flatness),max(flatness),min(flatness),median(flatness),std(flatness),...
           mean(flux),max(flux),min(flux),median(flux),std(flux),...
           mean(kurtos),max(kurtos),min(kurtos),median(kurtos),std(kurtos),...
           mean(skew),max(skew),min(skew),median(skew),std(skew),...
           mean(slope),max(slope),min(slope),median(slope),std(slope),...
           mean(spread),max(spread),min(spread),median(spread),std(spread),...
           mean(decrease),max(decrease),min(decrease),median(decrease),std(decrease),...
           mean(TonalPR),max(TonalPR),min(TonalPR),median(TonalPR),std(TonalPR),...
           mean(RMS),max(RMS),min(RMS),median(RMS),std(RMS),...
           mean(time_std),max(time_std),min(time_std),median(time_std),std(time_std),...
           mean(zcr),max(zcr),min(zcr),median(zcr),std(zcr),...
           mean(rollOff),max(rollOff),min(rollOff),median(rollOff),std(rollOff),...
           mean(pitchChroma,2)',min(pitchChroma,[],2)',max(pitchChroma,[],2)',median(pitchChroma,2)'];
           %mean(mfccs,2)',min(mfccs,[],2)',max(mfccs,[],2)',median(mfccs,2)',...%mean(max(mfccs)),mean(min(mfccs)),median(max(mfccs)),median(min(mfccs)),median(mean(mfccs)),...
           %,mean(max(pitchChroma)),mean(min(pitchChroma)),median(max(pitchChroma)),median(min(pitchChroma)),median(mean(pitchChroma))];
     

end